#!/bin/sh

BASE_DIR=$(dirname "$0")
JAVA_DIR="$BASE_DIR/java"
ZULU_VERSION="21.0.10"
ZULU_BUILD="21.48.17-ca"
ZULU_BASE_URL="https://cdn.azul.com/zulu/bin"

if [ -x "$JAVA_DIR" ]; then
    echo "Java already present."
    exit 0
fi

OS="$(uname -s)"
case "$OS" in
    Linux*)               OS="linux" ;;
    Darwin*)              OS="macos" ;;
    CYGWIN*|MSYS*|MINGW*) OS="win" ;;
    *)                    echo "Unsupported OS: $OS"; exit 1 ;;
esac

ARCH="$(uname -m)"
case "$ARCH" in
    x86_64|amd64)  ARCH="x64" ;;
    aarch64|arm64) ARCH="aarch64" ;;
    *)             echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac

if [ "$OS" = "win" ]; then
    EXT="zip"
else
    EXT="tar.gz"
fi

BASE_FILENAME="zulu${ZULU_BUILD}-jre${ZULU_VERSION}-${OS}_${ARCH}"
FILENAME="${BASE_FILENAME}.${EXT}"
URL="$ZULU_BASE_URL/$FILENAME"
TMP_FILE="$BASE_DIR/$FILENAME"

echo "Downloading $FILENAME."
curl -fL -o "$TMP_FILE" "$URL"

case "${OS}_${ARCH}" in
    linux_x64)      EXPECTED_SHA256="26ea2828c3111f2bfd3163b2f5dbd4d2429d7fdedf0a4b89d3065603c994dc50" ;;
    linux_aarch64)  EXPECTED_SHA256="62bfdbeb4e4bd69329d450e433222521dbde6aefd14c2a0a43055cc16d5aeed9" ;;
    macos_x64)      EXPECTED_SHA256="0dc3de9c4de5fe732a09bafe2103687c365c904ab9542043e89c829dd49e9e28" ;;
    macos_aarch64)  EXPECTED_SHA256="7c29d3232a163c366af3fda303bd54ffda22f41c16ba4c87f19b6adb91b1d232" ;;
    win_x64)        EXPECTED_SHA256="82b99c1cc9d0a8b4d6307a8ee38ae156acc63931b20263f159ec1909307e7ce9" ;;
    *)              echo "No checksum configured for this platform"; exit 1 ;;
esac

ACTUAL_SHA256="$(sha256sum "$TMP_FILE" | awk '{print $1}')"

if [ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]; then
    echo "Checksum verification failed."
    exit 1
fi
echo "Verified checksum."

if [ "$EXT" = "zip" ]; then
    unzip -q "$TMP_FILE" -d "$BASE_DIR"
else
    tar -xzf "$TMP_FILE" -C "$BASE_DIR"
fi

# Rename the newly created dir
mv "$BASE_FILENAME" "$JAVA_DIR"

rm "$TMP_FILE"

echo "Java set up."
