#!/bin/sh

# Check if there is a JRE in the "java" directory
if [ -x "./java/bin/java" ]; then
    JAVA_EXEC="./java/bin/java"
else
    # Check if java is in the PATH
    if ! command -v java > /dev/null 2>&1; then
        echo "ERROR: Java Runtime Environment not found. Please install Java or place it in the 'java' directory."
        exit 1
    else
        JAVA_EXEC="java"
    fi
fi

case "$(uname 2>/dev/null || echo unknown)" in
    CYGWIN* | MSYS* | MINGW*) # Windows
        BASE_DIR=$(cygpath -w "$(dirname "$0")")
        CLASS_SEPARATOR=";"
    ;;
    *) # Assume Unix-like
        BASE_DIR=$(dirname "$0")
        CLASS_SEPARATOR=":"
    ;;
esac

# Run the Java application using the current directory as the classpath
"$JAVA_EXEC" -cp "$BASE_DIR/*$CLASS_SEPARATOR$BASE_DIR/libs/*" com.github.trosenkrantz.raptor.Main "$@"
